name: Quoth The Vikings
on: [push]

jobs:
  terraform_default_job:
    runs-on: ubuntu-latest
    name: Using quoth_the_vikings action
    steps:
      - id: quoth_the_vikings
        uses: sturlabragason/quoth_the_vikings@main
      - name: Check outputs
        shell: pwsh
        run: echo ${{ steps.quoth_the_vikings.outputs.quote }}